server:
  port: 80
  servlet:
    context-path: /ok
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost/200ok?characterEncoding=UTF-8
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
